### ISSUE TITLE
Thanks for picking up

### ISSUE THREAD

**Issue by frostworx** [cherrryb0mb/typhon-launcher#1]
Hi there!
I'm the original author of typhon and just found your fork accidentally.

Thank you for keeping it up or better say revive it! :)

**Comment by shibowo** [comment]
Glad to see you here!

While I did get typhon to a state where it does run I still have a lot to fix before I can personally say I truly "revived" it (but hey, it runs now :) ). That said, I appreciate your thanks.

I have to thank you as well; after all,  typhon wouldn't exist at all if it wasn't for you!
